config/routes.rb
Rails.application.routes.draw do
  get 'accounts/regist'
  get 'accounts', to: 'accounts#regist'

  root :to =>'items#get'

  get 'items/get'
  get 'items', to: 'items#get'
  post 'items/get'

  #post 'items/upload', to: 'items#get'
  post 'items/upload'

  post 'accounts/regist'
  get 'accounts/regist'
  patch 'accounts/regist'

  get 'items/set', to: 'items#set'
  post 'items/set', to: 'items#set'

  get 'items/set_csv'
  post 'items/set_csv'

  get 'items/login_check'

  get 'items/output'
  post 'items/output'

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  require 'csv'
  require 'peddler'
  before_action :authenticate_user!, only: :get

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, :alert => exception.message
  end

  def get

    res = params[:data]
    logger.debug("Parameter=\n\n")
    logger.debug(res)
    @user = current_user.email

    current_email = current_user.email
    csv_data = CSV.read('app/others/csv/Flat.File.Toys.jp.csv', headers: true)
    gon.csv_head = csv_data

    if request.get? then

    else
      if res != nil then
        logger.debug(current_user.email)
        logger.debug("\n<=debug\n")
        parser = JSON.parse(res)
        result = parser[0]
        counter = parser[1]

        logger.debug(counter)
        logger.debug("\n<=debug\n")
        logger.debug(result)

        res = result

        i = counter
        maxnum = 10
        process = 0
        while i < result.length

            url = result[i][0]
            if url != "" && url != nil  then
              charset = nil
              html = open(url) do |f|
                charset = f.charset # 文字種別を取得
                f.read # htmlを読み込んで変数htmlに渡す
              end
              doc = Nokogiri::HTML.parse(html, nil, charset)
              if doc.xpath('//p[@class="ptsFin"]')[0] == nil then

                #商品が出品中の場合
                title = doc.xpath('//h1[@class="ProductTitle__text"]').text.gsub("\n","")
                productinfo = doc.xpath('//li[@class="ProductDetail__item"]')
                condition = /<th class="ProductTable__th">状態<\/th>([\s\S]*?)\/li>/.match(html)
                if condition != nil then
                  condition = condition[1]
                  condition = /<li class="ProductTable__item">([\s\S]*?)</.match(condition)[1]
                  condition = condition.gsub(/\R/, "")
                  condition = condition.strip
                end
                k = 0
                while k < productinfo.length
                  str = productinfo[k].text
                  if str.include?("オークションID") == true then
                    auctionID = productinfo[k].inner_html.match(/pan>([\s\S]*?)<\/dd/)[1]
                  end
                  k += 1
                end
                k = 0


                priceType = doc.xpath('//div[@class="Price Price--current"]//dd[@class="Price__value"]')
                if priceType[0] != nil then
                  listPrice = priceType[0].text.gsub("\n","")

                  if listPrice.include?("（税 0 円）") == true then
                    listPrice = listPrice.gsub(/（税 0 円）/,"")
                    listPrice = CCur(listPrice)
                  else
                    listPrice = listPrice.match(/税込([\s\S]*?)円/)[1]
                    listPrice = CCur(listPrice)
                  end
                else
                  listPrice = 0
                end

                priceType = doc.xpath('//div[@class="Price Price--buynow"]//dd[@class="Price__value"]')
                if priceType[0] != nil then
                  binPrice = priceType[0].text.gsub("\n","")
                  if binPrice.include?("（税 0 円）") == true then
                    binPrice = binPrice.gsub(/（税 0 円）/,"")
                    binPrice = CCur(binPrice)
                  else
                    binPrice = binPrice.match(/税込([\s\S]*?)円/)[0]
                    binPrice = binPrice.gsub(/税込/,"")
                    binPrice = CCur(binPrice)
                  end
                else
                  binPrice = 0
                end

                bitnum = doc.xpath('//dd[@class="Count__number"]')[0].text
                bitnum = bitnum.slice(0,bitnum.length-4)

                restTime = doc.xpath('//dd[@class="Count__number"]')[1].text
                restTime = restTime.slice(0,restTime.length-4)

                images = doc.xpath('//div[@class="ProductImage__inner"]')
                image = []

                k = 0

                while k < images.length
                  str = images[k].inner_html
                  image[k] = str.match(/src="([\s\S]*?)"/)[1]
                  k += 1
                end

              else
                #オークションが終了している場合

                title = doc.xpath('//h1[@property="auction:Title"]')[0].text
                title = "[終了したオークション]" + title

                auctionID = doc.xpath('//td[@property="auction:AuctionID"]')[0]
                if auctionID != nil then
                  auctionID = auctionID.text
                end
                condition = doc.xpath('//td[@property="auction:ItemStatus"]')[0]
                if condition != nil then
                  condition = condition.text
                  condition = condition.gsub(/\R/, "")
                  condition = condition.strip
                end

                binPrice = ""
                checkTax = doc.xpath('//p[@class="decTxtTaxIncPrice"]')[0]
                if checkTax != nil then
                  checkTax = checkTax.text
                end

                logger.debug(url)

                listPrice = doc.xpath('//p[@class="decTxtBuyPrice Price__value"]')[0]
                if listPrice != nil then
                  listPrice = doc.xpath('//p[@class="decTxtBuyPrice Price__value"]')[0].text
                else
                  listPrice = doc.xpath('//p[@class="decTxtAucPrice Price__value"]')[0].text
                end
                listPrice = CCur(listPrice)
                if listPrice != nil then
                  if listPrice.include?("%") then
                    listPrice = /^([\s\S]*?)\s/.match(listPrice)[1]
                  end
                end
                binPrice = 0
                bitnum = doc.xpath('//b[@property="auction:Bids"]')[0]
                if bitnum != nil then
                  bitnum = bitnum.text
                end

                restTime = "終了"
                k = 0
                image = []
                while k < 3
                  images = doc.xpath('//img[@id="imgsrc' + (k+1).to_s + '"]')
                  if images[0] != nil then
                    image[k] = images[0].attribute("src").value
                  end
                  k += 1
                end
              end
            else
              title = ""
              auctionID = ""
              listPrice = ""
              binPrice = ""
              condition = ""
              bitnum = ""
              restTime = ""
              k = 0
              image = []
              while k < 3
                image[k] = ""
                k += 1
              end
            end
            title = title.gsub("\t", "")

            res[i] = [url,title,auctionID,listPrice,binPrice,condition,bitnum,restTime,image[0],image[1],image[2]]

            process += 1
            if process > maxnum - 1 then
              break
            end
            i += 1
        end

        logger.debug("\ndebug=>\n")
        @result = res
        render json: res
      end
    end
  end

  def upload
    logger.debug("\n\n\n")
    logger.debug("Debug Start!")
    current_email = current_user.email
    user = Account.find_by(email: current_email)
    aws = user.AWSkey
    skey = user.skey
    seller = user.sellerId

    res = params[:data]

    #client = MWS.sellers(
    #  primary_marketplace_id: "A1VC38T7YXB528",
    #  merchant_id: seller,
    #  aws_access_key_id: aws,
    #  aws_secret_access_key: skey
    #)
    client = MWS.feeds(
      primary_marketplace_id: "A1VC38T7YXB528",
      merchant_id: seller,
      aws_access_key_id: aws,
      aws_secret_access_key: skey
    )

    res1 = JSON.parse(res)
    #res1 = [["a","b","c"],[1,2,3],["村上","りえ","ネコ"]]

    logger.debug("Pre Feed Content is \n\n")
    logger.debug(res1)

    kk = 0
    feed_body = ""
    while kk < res1.length
      feed_body = feed_body + res1[kk].join("\t")
      feed_body = feed_body + "\n"
      kk += 1
    end

    new_body = feed_body.encode(Encoding::Windows_31J)

    #return

    logger.debug("Feed Content is \n\n")
    logger.debug(new_body)

    feed_type = "_POST_FLAT_FILE_LISTINGS_DATA_"
    parser = client.submit_feed(new_body, feed_type)
    doc = Nokogiri::XML(parser.body)

    submissionId = doc.xpath(".//mws:FeedSubmissionId", {"mws"=>"http://mws.amazonaws.com/doc/2009-01-01/"}).text

    process = ""
    err = 0
    while process != "_DONE_" do
      sleep(25)
      list = {feed_submission_id_list: submissionId}
      parser = client.get_feed_submission_list(list)
      doc = Nokogiri::XML(parser.body)
      process = doc.xpath(".//mws:FeedProcessingStatus", {"mws"=>"http://mws.amazonaws.com/doc/2009-01-01/"}).text
      logger.debug(doc)
      err += 1
      if err > 1 then
        break
      end
    end


    parser = client.get_feed_submission_result(submissionId)
    doc = Nokogiri::XML(parser.body)
    logger.debug(doc)
    logger.debug("\n\n")
    #submissionId = doc.match(/FeedSubmissionId>([\s\S]*?)<\/Feed/)[1]
    #parser.parse # will return a Hash object

    res = ["test"]
    render json: res
  end

  def set

    if request.post? then
      res = params[:data]
      res = JSON.parse(res)
      ptable = res['price']
      ttable = res['title']
      ftable = res['fixed']
      keytable = res['keyword']

      current_email = current_user.email

      temp = Setting.find_by(email:current_email)
      logger.debug("Account is search!!\n\n")
      logger.debug(Setting.select("price"))
      if temp != nil then
        logger.debug("Account is found!!!")
        user = Setting.find_by(email:current_email)
        user.update(fixed: ftable, keyword: keytable, title: ttable, price: ptable )
        user.save
      else
        user = Setting.create(
          email: current_user.email,
          fixed: ftable,
          keyword: keytable,
          price: ptable,
          title: ttable,
        )

      end
    else
      logger.debug("Access is GET")
      current_email = current_user.email
      temp = Setting.find_by(email:current_email)

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/get.html.erb
<div class="container">

  <h1 class="bg-primary" style="line-height:50pt;text-indent:20pt">Xmaster ～アマゾン‐ヤフオク販売ツール～</h1>

  <h4><strong>ログイン中：<%= @user %></strong></h4>
  <%= link_to "MWSアカウント管理", accounts_path, :target=>["_blank"] %>
  &nbsp;
  <%= link_to "出品パラメータ設定", "/items/set", :target=>["_blank"] %>
  &nbsp;
  <%= link_to 'ログアウト', destroy_user_session_path, method: :get %>
  &nbsp;&nbsp;
  <%= link_to "管理者専用", "/admin" %>

  <br>
  <br>
  <h4><strong>ヤフオクから情報取得</strong></h4>
  <button id="done" class="btn btn-primary">ヤフオク情報取得</button>
  &nbsp;
  <button id="make_csv" class="btn btn-primary">CSV作成</button>
  &nbsp;
  <% @tt=Time.now.strftime("_%H%M%S") %>
  <a href="#" id="csv_output" download="list<%= @tt %>.txt" class="btn btn-warning">CSV出力</a>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  <button id="csv_upload" class="btn btn-danger">アップロード</button>
  <br>
  <br>
  <br>
  <div class="progress progress-striped active">
    <div class="progress-bar" style="width: 0%" id="progressbar"></div>
  </div>
  <div id="main"></div>
  <br>
  <h4><strong>アップロードCSVの確認</strong></h4>
  <div id="selected"></div>
  <div id="csv"></div>
</div>

app/views/items/get.js.erb
var mydata = [
    ["https://page.auctions.yahoo.co.jp/jp/auction/e240280599","title1","id1","p1","p1"],
    ["","title2","id2","p2","p2"],
    ["","title3","id3","p3","p3"]
];
var container = document.getElementById('main');
var handsontable = new Handsontable(container, {
  /* オプション */
  // 表示データ
  data: mydata,
  // 列ヘッダー
  rowHeaders: true,
  // 行ヘッダー
  colHeaders: ["ヤフオク商品URL","商品タイトル","オークションID","現在価格","即決価格"],
  // 最大行数
  maxCols: 6,
  // 最大列数
  maxRows: 5,
  //オプション
  columns:[
    {},
    {readOnly: true},
    {readOnly: true},
    {readOnly: true},
    {readOnly: true}
  ]
});

$("#done").click(function () {
    //var myData = {data : handsontable.getData()};
    var myData = handsontable.getData();
    myData = JSON.stringify(myData);
    myData = {data: myData};

    $.ajax({
        url: "/items/get.js",
        type: "POST",
        data: myData,
        success: function (myData) {
          alert('ok');
        },
        error: function (myData) {
          alert("NG");
        }
    });
  });

app/views/items/items_set.js.erb

var maxColnum = 2;
var maxRownum = 10;
var price_data = [];
var title_data = [];
var colOption = [];

var idata = gon.udata;
var pdata = idata['price'];
var fdata = idata['fixed'];
var tdata = idata['title'];
var kdata = idata['keyword'];

for(var i=0; i < maxRownum; i++){
  price_data[i] = [];
  title_data[i] = [];
  for(var j=0; j < maxColnum; j++){
    price_data[i][j] = i*2000;
    title_data[i][j] = "";
  }
  colOption[i] = {readOnly: true};
}
colOption[0] = {readOnly: false};

var price_container = document.getElementById('price_table');
var price_handsontable = Handsontable(price_container, {
  /* オプション */
  width: 480,
  height: 240,
  //data: price_data,
  data: pdata,
  rowHeaders: true,
  colHeaders: ["ヤフオク販売価格","アマゾン販売価格"],
  maxCols: maxColnum,
  maxRows: maxRownum,
  manualColumnResize: true,
  autoColumnSize: false,
  colWidths:[200,200]
});

var title_container = document.getElementById('title_table');
var title_handsontable = Handsontable(title_container, {
  /* オプション */
  width: 480,
  height: 240,
  //data: title_data,
  data: tdata,
  rowHeaders: true,
  colHeaders: ["置換前","置換後"],
  maxCols: maxColnum,
  maxRows: maxRownum,
  manualColumnResize: true,
  autoColumnSize: false,
  colWidths:[200,200]
});

var int_data =[];
var rnum = 9;
for(var i=0; i < rnum; i++){
  int_data[i] = [];
  int_data[i][0] = "";
  int_data[i][1] = "";
}

int_data[0][0] = "feed_product_type"
int_data[1][0] = "quantity"
int_data[2][0] = "recommended_browse_nodes"
int_data[3][0] = "fulfillment_latency"
int_data[4][0] = "condition_type"
int_data[5][0] = "condition_note"
int_data[6][0] = "merchant_shipping_group_name"

var fix_container = document.getElementById('fix_table');
var fix_handsontable = Handsontable(fix_container, {
  /* オプション */
  width: 800,
  height: 240,
  //data: int_data,
  data: fdata,
  rowHeaders: true,
  colHeaders: ["項目名","値"],
  maxCols: maxColnum,
  maxRows: maxRownum,
  manualColumnResize: true,
  autoColumnSize: true,
  colWidths:[200,200]
});

var brand_data = [];
for(var i=0; i < 20; i++){
  brand_data[i] = [];
  brand_data[i][0] = "";
  brand_data[i][1] = "";
  brand_data[i][2] = "";
  brand_data[i][3] = "";
  brand_data[i][4] = "";
}

var brand_container = document.getElementById('brand_table');
var brand_handsontable = Handsontable(brand_container, {
  /* オプション */
  width: 1000,
  height: 240,
  //data: brand_data,
  data: kdata,
  rowHeaders: true,
  colHeaders: ["キーワード","brand_name","manufacturer","recommended_browse_nodes","generic_keywords"],
  maxCols: 5,
  maxRows: maxRownum,
  manualColumnResize: true,
  autoColumnSize: false,
  colWidths:[200,150,150,250,400]
});



$("#save").click(function () {
  var pricedata = price_handsontable.getData();
  var titledata = title_handsontable.getData();
  var keydata = brand_handsontable.getData();
  var fixdata = fix_handsontable.getData();

  var senddata = {price: pricedata, title: titledata, keyword: keydata, fixed: fixdata};
  senddata = JSON.stringify(senddata);

  myData = {data: senddata};

  $.ajax({
    url: "/items/set",
    type: "POST",
    data: myData,
    dataType: 'json',
    success: function (myData) {
      alert("OK");
      //handsontable.loadData(myData);
    },
    error: function (myData) {
      //handsontable.loadData(myData);
      alert("NG");
    }
  });
});

app/views/items/login_check.html.erb
<h1>Login</h1>
<p><%= @user %></p>

app/views/items/set.html.erb
<div class="container">
  <h1 class="bg-primary" style="line-height:50pt;text-indent:20pt">出品用CSVの各情報の詳細設定</h1>

  <h4><strong>CSVの作成に必要な情報を記入</strong></h4>
  <br>

  <button id="save" class="btn btn-primary">保存</button>
  <br>
  <br>
  <table class="table">
    <tr>
      <h4><strong>定型パラメータの設定</strong></h4>
    </tr>
    <tr>
      <div id="fix_table">
    </tr>
  </table>

  <table class="table">
    <tr>
      <td colspan="2"><h4><strong>キーワードとの紐づけ設定</strong></h4></td>
    </tr>
    <tr>
      <td colspan="2"><div id="brand_table"></td>
    </tr>
  </table>

  <table class="table">
    <tr>
      <td><h4><strong>販売価格テーブルの設定</strong></h4></td>
      <td><h4><strong>タイトル置換テーブルの設定</strong></h4></td>
    </tr>
    <tr>
      <td><div id="price_table"></td>
      <td><div id="title_table"></td>
    </tr>
  </table>

app/views/items/upload.html.erb
<h1>CSVの確認</h1>
<p>アップロードするCSVを確認してください</p>